import dotenv from 'dotenv';
import { logger } from '../utils/logger';

dotenv.config();

// Configuration for the application
export const config = {
  // Server config
  port: process.env.PORT || 3001,
  
  // Database
  databasePath: process.env.DATABASE_PATH || './database/app.db',
  
  // JWT & Encryption
  jwtSecret: process.env.JWT_SECRET || 'youtube-tv-secret-key',
  encryptionKey: process.env.ENCRYPTION_KEY || 'youtube-tv-encryption-key',
  
  // Frontend URL
  frontendUrl: process.env.FRONTEND_URL || 'http://localhost:5173',

  // Path to Netscape-format cookies file for yt-dlp
  cookiesPath: process.env.COOKIES_PATH || './cookies.txt',

  // Path to pre-exported subscriptions JSON (generated by export-cookies.sh)
  subscriptionsPath: process.env.SUBSCRIPTIONS_PATH || './subscriptions.json'
};

logger.log('YouTube TV Configuration:', {
  port: config.port,
  database: config.databasePath
});